language: node_js
node_js:
  - "11.0"
  
branches:
  only:
    - master
    
before_script:
  - npm install -g @angular/cli
  - npm install codecov -g
  
script:
  - npm install
  - npm run build

after_success:
  - codecov
